[cicd] re-user actions Thu Apr 27 13:26:57 CEST 2023

diff --git a/.github/workflows/matrix_call.yaml b/.github/workflows/matrix_call.yaml
--- a/.github/workflows/matrix_call.yaml
+++ b/.github/workflows/matrix_call.yaml
@@ -38,6 +38,7 @@ jobs:
         run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
       - name: Show initial info
         run: |
+          exit 1 # fail for debug
           echo "Environment is: ${{ github.event.inputs.environment }}"
           echo "Initiated by: ${{ github.actor }}"
           echo "Branch is: ${{ github.head_ref || github.ref_name }}"
